In [54]:
import os
import triangle as tr
import numpy as np
import plotly.figure_factory as ff
from scipy.io import savemat

In [55]:
point_0 = [-0.099, -0.1]
point_1 = [-0.006, -0.007]
point_2 = [-0.006, 0.007]
point_3 = [-0.099, 0.1]
point_4 = [0.099, 0.1]
point_5 = [0.006, 0.007]
point_6 = [0.006, -0.007]
point_7 = [0.099, -0.1]
point_8 = [-0.066, 0]
point_9 = [0.066, 0]

In [56]:
vertices = np.array([
    point_0, point_1, point_2, point_3, point_4, point_5, point_6, point_7, point_8, point_9
])

segments = np.array([
    [0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 0], [8, 9], [2, 5], [1, 6]
])

In [57]:
adaptative_bowtie = {
    'vertices': vertices,
    'segments': segments
}

In [62]:
# Maillage avec contraintes de qualité
mesh_adaptative_bowtie = tr.triangulate(adaptative_bowtie, 'pq30a0.00001Dj')

# Extraire les sommets et les triangles
points = np.zeros((3, mesh_adaptative_bowtie['vertices'].shape[0]))
points[:2, :] = np.array(mesh_adaptative_bowtie['vertices']).T
triangles = np.ones((4, mesh_adaptative_bowtie['triangles'].shape[0]), dtype=int)
triangles[:3, :] = np.array(mesh_adaptative_bowtie['triangles']).T

In [63]:
print(points)
print(f"taille de points : {points.shape}")

[[-0.099      -0.006      -0.006      ...  0.09623786  0.09509375
   0.09314063]
 [-0.1        -0.007       0.007      ... -0.09723786 -0.1
  -0.09757297]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]]
taille de points : (3, 1718)


In [64]:
print(triangles)
print(f"taille de triangles : {triangles.shape}")

[[  16   28   88 ... 1716 1681 1666]
 [  17   34   87 ...    7 1717 1716]
 [   9    6   89 ... 1715 1667 1717]
 [   1    1    1 ...    1    1    1]]
taille de triangles : (4, 3193)


In [65]:
# Normalisation pour l'aspect ratio
x_, y_, z_ = points
fig_scale = max(max(x_) - min(x_), max(y_) - min(y_))
x_scale = (max(x_) - min(x_)) / fig_scale
y_scale = (max(y_) - min(y_)) / fig_scale
z_scale = 0.3  # Z scale arbitraire pour une meilleure visualisation

# Création de la figure 3D avec Plotly
fig = ff.create_trisurf(
    x=x_,
    y=y_,
    z=z_,
    simplices=triangles[:3, :].T,
    color_func=list(range(len(triangles[:3, :].T))),  # Couleurs basées sur les indices des triangles
    show_colorbar=True,
    title="Maillage triangulaire",
    aspectratio=dict(x=x_scale, y=y_scale, z=z_scale)
)
# Afficher la figure
fig.show()

In [ ]:
# Crée un dictionnaire contenant toutes les données à sauvegarder
data = {
    'p' : points,
    't' : triangles
}
save_folder_name = 'data'
save_file_name = 'adaptative_bowtie.mat'
full_save_path = os.path.join(save_folder_name, save_file_name)  # Chemin complet pour la sauvegarde

# Vérifie si le dossier existe, sinon crée le dossier
if not os.path.exists(save_folder_name): # Vérification et création du dossier si nécessaire
    os.makedirs(save_folder_name)
    print(f"Directory '{save_folder_name}' created.")

# Sauvegarde les données dans le fichier MAT
savemat(full_save_path, data)
print(f"Data saved successfully to {full_save_path}")